version: "3.7"
services:
  php:
    build: ./docker/php 
    volumes:
      - .:/code:cached
      - ./docker/data/sock:/sock
    environment:
      DEV: 1
    env_file:
      - dev.env
  nginx:
    image: nginx:1.21.0
    ports:
      - 80:80
    volumes:
      - .:/code:cached
      - ./docker/data/sock:/sock
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0.16
    ports:
      - "3306:3306"
    env_file:
      - dev.env
  adminer:
    image: adminer:latest
    ports:
      - 88:8080
    depends_on:
      - db
